### ISSUE TITLE
ReasonML language

### ISSUE THREAD

**Issue by idkjs** [Simon-Initiative/authoring-client#764]
Is it possible to support `reasonml` as a coding language?

Thanks for sharing this great work.

Peace/Love

**Comment by darrensiegel** [comment]
Thanks for taking the time to file this issue.

At this point in time, we will not be extending codeblock language highlighting support to target any additional languages. 

We are building out the next generation of our curriculum delivery platform (see Simon-Initiative/oli-torus), which will support OCaml and ReasonML.
